### ISSUE TITLE
Does not work with Rubicure v1.0.5 

### ISSUE THREAD

**Issue by greymd** [greymd/cureutils#19]
```
root@118214edf78c:~/cureutils# bundle exec bin/cure echo -q -p cure_echo
bundler: failed to load command: bin/cure (bin/cure)
NoMethodError: undefined method `include?' for nil:NilClass
  /usr/local/bundle/gems/rubicure-1.0.5/lib/rubicure/girl.rb:215:in `respond_to_missing?'
  /usr/local/bundle/gems/hashie-3.5.5/lib/hashie/extensions/method_access.rb:32:in `respond_to?'
  /usr/local/bundle/gems/hashie-3.5.5/lib/hashie/extensions/method_access.rb:32:in `respond_to?'
  /usr/local/bundle/gems/hashie-3.5.5/lib/hashie/extensions/method_access.rb:72:in `respond_to?'
  /usr/local/bundle/gems/hashie-3.5.5/lib/hashie/extensions/method_access.rb:113:in `respond_to?'
  /root/cureutils/lib/cureutils/logic/echo_logic.rb:55:in `original_transform'
  /root/cureutils/lib/cureutils/logic/echo_logic.rb:44:in `print_results'
  /root/cureutils/lib/cureutils/cli.rb:132:in `echo'
  /usr/local/bundle/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
  /usr/local/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
  /usr/local/bundle/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
  /usr/local/bundle/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
  bin/cure:10:in `<top (required)>'
```

This is caused by the bug given by rubicure side?

```
$ irb -r rubicure
irb(main):001:0> Cure.echo.respond_to?(:transform_styles)
NoMethodError: undefined method `include?' for nil:NilClass
        from /Users/yasuhiro.yamada/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rubicure-1.0.5/lib/rubicure/girl.rb:215:in `respond_to_missing?'
        from /Users/yasuhiro.yamada/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hashie-3.4.6/lib/hashie/extensions/method_access.rb:32:in `respond_to?'
        from /Users/yasuhiro.yamada/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hashie-3.4.6/lib/hashie/extensions/method_access.rb:32:in `respond_to?'
        from /Users/yasuhiro.yamada/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hashie-3.4.6/lib/hashie/extensions/method_access.rb:72:in `respond_to?'
        from /Users/yasuhiro.yamada/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hashie-3.4.6/lib/hashie/extensions/method_access.rb:113:in `respond_to?'
        from (irb):1
        from /Users/yasuhiro.yamada/.rbenv/versions/2.3.0/bin/irb:11:in `<main>'
```

**Comment by greymd** [comment]
`transform_calls:` element does not exist in the [movie.yml](https://github.com/sue445/rubicure/blob/master/config/girls/movie.yml).
But Cure echo does not have any phrases during her transformation...hmm...
